spring:
  datasource:
    url: jdbc:h2:D:/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-ui
  profiles:
    active: development
  server:
    port: 8080
  jpa:
    hibernate:
      ddl-auto: update
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-ui/**